### ISSUE TITLE
is adorn_totals counter intuitive?

### ISSUE THREAD

**Issue by dsdesrosiers** [sfirke/janitor#185]
Sam -

Has anybody offered feedback that adorn_totals("row") and adorn_totals("col") imply the reverse of what you get? It may totally be me, but since it seems to be still the dev package I thought I'd throw this out.  I expected adorn_totals("row") to give me the row total to the right and adorn_totals("col") to give me the totals at the bottom.

Danielle

**Comment by sfirke** [comment]
Thanks for sharing this, Danielle.  I have not heard this before.  But I see it.  It's adding a totals row, but that row is the product of summing the columns ... the whole thing is 😕.

I've thought on this a bit and to me it comes down to the word ordering.  `adorn_row_totals()` would feel to me like adding totals to each row, i.e., a new column.  While `adorn_totals_row` would be creating a totals row and adding it [to the bottom].  I like the latter a bit more, in part because of similar syntax between `adorn_totals("row")` and `adorn_totals("col")`.

So while it's unfortunately still ambiguous, I don't think switching it would make it clearer.  If anyone has an idea for a clearer, equally simple naming scheme I'm open to it.

I think it's too clunky to to have "a" in there but `adorn_a_totals("row")` would be clearer, expressing the singular vs the plural... 🤔

**Comment by dsdesrosiers** [comment]
I agree that adorn_totals_row is the best option because in my head now I expect the output to be a row whereas if it's the argument to a function I assume the function will work on the argument I pass (hence totaling the row as a new column. 

If you decide to leave it unchanged (which I would get because if you split them then you have two functions to maintain unless you created small functions that called the adorn_totals function with the appropriate arguments - maybe not considered nice programming) I'd be happy to help with some examples.
