### ISSUE TITLE
Remove totals row from sheet

### ISSUE THREAD

**Issue by statzhero** [sfirke/janitor#194]
## Feature requests

I'd find a function useful that removes the totals row of an Excel spreadsheet. 

In fact, there could be an automatic warning based on keywords (total, totals, sum etc) in case a user forgets about it.

**Comment by sfirke** [comment]
I'm cleaning up some old issues, I apologize for not acknowledging this in the first place.  Given where janitor and I are currently, I don't have the cycles to implement something like this.

Also it would be hard to write a generalized version since a totals row can take different forms that would be hard to machine-identify in a trustworthy and reliable way.

I suggest users just filter it out each time manually unfortunately.
