### ISSUE TITLE
Feature Request? Elevate a Row to a Header

### ISSUE THREAD

**Issue by billdenney** [sfirke/janitor#207]
As described in my last issue (#206), I often work with messy data.  One common refrain is that upon load, I sometimes need to change which row is the header.

```r
#' Elevate a row to be the header of a data.frame
#'
#' @param dat The input data.frame
#' @param row_number The row of \code{dat} to make into the header
#' @param remove_row Remove \code{row_number} from the return value?
#' @param remove_rows_above If \code{row_number != 1}, remove rows
#'   \code{1:(row_number-1)}?
#' @param force_unique Ensure that the column names are unique?
#' @return A data frame with new names and a cleaned-up header
#' @example
#' data.frame(X__1=c(NA, "Title", 1:3),
#'            X__2=c(NA, "Title2", 4:6),
#'            stringsAsFactors=FALSE) %>%
#'   row_to_header(row_number=2)
#' @export
row_to_header <- function(dat, row_number=1, remove_row=TRUE, remove_rows_above=TRUE, force_unique=TRUE) {
  # Check inputs
  if (length(row_number) != 1) {
    stop("row_number must be a scalar")
  }
  new_names <- as.character(unlist(dat[row_number,], use.names=FALSE))
  if (force_unique) {
    new_names <- make.unique(new_names, sep="_")
  } else if (any(duplicated(new_names))) {
    warning("Row ", row_number, " does not provide unique names (consider the force_unique argument)")
  }
  names(dat) <- new_names
  rows_to_remove <- c(
    if(remove_row) {
      row_number
    } else {
      c()
    },
    if (remove_rows_above) {
      seq_len(row_number-1)
    } else {
      c()
    })
  if (length(rows_to_remove)) {
    dat[-(rows_to_remove),,drop=FALSE]
  } else {
    dat
  }
}

data.frame(X__1=c(NA, "Title", 1:3),
           X__2=c(NA, "Title2", 4:6),
           stringsAsFactors=FALSE) %>%
  row_to_header(row_number=1)
data.frame(X__1=c(NA, "Title", 1:3),
           X__2=c(NA, "Title2", 4:6),
           stringsAsFactors=FALSE) %>%
  row_to_header(row_number=2)
```

**Comment by sfirke** [comment]
This is a great idea! I might be a little slow giving feedback, running the
code, Etc as I'm expecting a baby this week but I have definitely had to do
this, and I think it's perfectly in scope for the janitor package.

I appreciate your thorough feature request including writing a documented
function! 😍

**Comment by billdenney** [comment]
Congratulations!  (And no worried on slow feedback. :) )

**Comment by sfirke** [comment]
This is great and would be a valuable addition to janitor!  Please go ahead and open a pull request to a branch containing this code.  If possible, please give me commit access to that branch.

The branch will need:

- [ ] This function
- [ ] Documentation - your documentation is good, just run devtools::document() to create the .Md
- [ ] Unit tests - let me know how familiar or not you are with this and I can provide guidance.  Beyond basic 100% coverage, one thing to add coverage for is whether it works on both a tibble and on a base data.frame
- [ ] An addition to NEWS.Md, recognizing your contribution, and inclusion in a vignette

Bill, would you be up for submitting this pull request?

As to the actual function itself, some thoughts I have reading the code:

- what do you or others think about "names" instead of "header", in the function name and documentation?  "names" seems like a more common R term to me.
- re: the `remove_` arguments, are these necessary - that is, is there ever a situation in which one would want to keep the row in the data or the rows above it?  The former, in particular, seems unlikely to me.
- I think you could remove the `force_unique` argument because that's a separate purpose so should be handled by a separate function.  I could see someone running `dat %>% row_to_names(7) %>% clean_names()` - or whatever name cleaning convention suits them

Again, thanks Bill for your generosity in sharing this idea and code.

**Comment by billdenney** [comment]
I am up for submitting the pull request.  And, I'm familiar with `testthat`.

For your thoughts:

* You're right, `names` makes more sense than `header`.
* I have had a few (bad) examples when I needed to keep the rows above the header.  In one case, I received the header at the bottom of the data (it baffled me that someone thought that best).  Another example I've seen is when the header is in the second row and the units were in the first row, so I needed to perform two separate steps to get all the info out that I needed.
* For `remove_row`, I sometimes want to perform additional operations on the row headers before totally dropping them.  As an example, when the header was provided as "value (units)" (like "glucose (mmol/L)"), I want to first set it to the header and then extract the units then remove the row.  It's preferable to do the unit extraction as a second step (at least the way I do my data management).
* Removing `force_unique` makes sense.  I lean toward keeping a warning if there are duplicates just so the user is informed if they may have an accidental errors down the line.  Does that make sense?

**Comment by sfirke** [comment]
Yep, I agree with all of that: I'm sold on keeping the `remove_row` and `remove_rows_above` arguments and I like throwing a warning if the names are not unique.

**Comment by billdenney** [comment]
I think that I did everything for the pull request.  The change to NEWS.md may not be stylistically just what you were looking for-- please modify as desired.  Also, the vignette addition changed a few other things that appear related to both changes in `janitor` and perhaps differences in `tibble`.

Let me know if you have any modifications you'd like.

**Comment by sfirke** [comment]
Hey Bill, one more thought on this.  If column names were in a row, they'll have distorted the class of those columns: numerics will be characters, and factors will have a false level (the col name).

What do you think about, after the elevating names occurs and removal of row(s) has taken place, converting columns that now consist solely of numbers to numeric and removing the now-missing level from factor columns?

It seems like the likely next step for the user, and a tedious one ... but also feels kinda heavyweight to program.

**Comment by billdenney** [comment]
... Maybe those should be noted as common follow-up functions in the documentation.
