### ISSUE TITLE
Possible to restrict adorn_pct_formatting() to proportion columns?

### ISSUE THREAD

**Issue by elinw** [sfirke/janitor#231]
I'm working on creating an adorn_cumulative function to show the cumulative frequencies. Ultimately I would like to add cumulative proportion and to be able to display with percent formatting.  Currently the existing adorn_percent_formatting applies to every column to the right except the totals and the first numeric column.  This makes sense as long as you only have one numeric column.  However with the cumulative n added it  changes that n to percents (so 256 becomes 25600%).  I was wondering if you would accept a pull request 
that would make adorn_pct_formatting() more generally useful by restricting its application to columns were all values are between 0 and 1 (and possibly that sum to 1 or no more than 1).  It's true that 125% is a valid value but it's not something that is possible inside a tabyl created by janitor (though it could come from a non-tabyl  being processed by janitor).     

```r
adorn_pct_formatting(mtcars)
```
Once I have it all working, I'd be happy to contribute my cumulative functions if they are of interest.

**Comment by sfirke** [comment]
Thanks for this suggestion!  I agree that an `adorn_cumulative` would be handy, I have written a crude version for my own use.  Do you think it has an application to a two-way tabyl (crosstab)?  I see its clear application as to a one-way tabyl, and if we limit it only to that, implementation may be easier.  `one-way` vs. `two-way` is encoded as an attribute of the tabyl.  If running on a one-way tabyl, `adorn_cumulative` would add a column of cumulative Ns and a column of cumulative %s.

This would sidestep the issue of which columns `adorn_percent_formatting` applies to.  Which is a real issue, to be sure, but feels bigger to me... other `adorn_` functions have that problem, with the root cause being that they were designed to work on the result of `tabyl` but in practice users seek to apply them to other kinds of count tables that they generated.  And I would like to serve that purpose, but it raises bigger issues like, should the `adorn_` functions provide the option of tidyselect-ing columns to apply to?  Which to me feels like janitor 2.0 or even spinning `tabyl` and `adorn_*` off into their own package with a from-the-ground-up redesign.

Do you think it's worth implementing `adorn_cumulative` to work on just a single-variable one-way tabyl in the meantime?

**Comment by elinw** [comment]
We had a discussion in our group and felt that cumulative is usually used for one way so I didn't implement  two way; I could definitely see a use case for two way existing but I'm not sure what it is.    
It would be really nice to be able to use the tidy select operators, that would really simplify things.  I agree that people are probably adding all kinds of things.  
Tabyl is really well along the way to being the missing cross tab system in R.  So I would definitely agree with the idea of eventually spinning it off.  I also have an implementation and I've seen other people's but with my students I want them to use established packages which is why I decided to implement the cumulative functionality as add ons.  But right now it's kind of overly verbose.

**Comment by sfirke** [comment]
Independent of the tidyselect and adorn_pct_formatting() issues, let's add adorn_cumulative() as a function that runs on one-way tabyls.  I'll open a new issue, tag you in, and share what I've been using.

**Comment by sfirke** [comment]
I just implemented controlling which columns the `adorn_` functions apply to, using the new `...` argument!
