### ISSUE TITLE
Are the adorn functions still relevant given the gt package?

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#265]
In contemplating issues like #219 , I was guided to the gt package: https://github.com/rstudio/gt

Looks like it accepts an input data.frame that is a table.  So `janitor::tabyl` could feed in.  But then it appears to do the formatting of the table.  And the features of that package, time invested in it, and skill of the developers dwarf the janitor `adorn_` functions it would replace.

I haven't yet used `gt` to format the results of a `tabyl`.  Need to do that.  For anyone who has, is there a need that the `adorn_` functions meet that isn't met by gt?

**Comment by sfirke** [comment]
I guess `adorn_percentages()` looks still useful, b/c it modifies the values of the numbers (while _gt_ only formats, doesn't do math?).

**Comment by jarekbryk** [comment]
Yes, because (the way I use janitor) is a quick and pretty formatting of glance-able tables. I would only use gt if I had to produce a "serious" report or a large number of tables etc., mainly for other people to use. Janitor and adorn_ are very useful for exploratory mucking about the data and maybe putting them on a quick plot (with tableGrob from gridExtra). Keep up the good work :-)

**Comment by sfirke** [comment]
I agree now, these are for quick ones.  A different niche.  I like the tip on tableGrob to put them on a plot.  Thanks for the supportive note @jarekbryk !
