### ISSUE TITLE
clean names to proper names?

### ISSUE THREAD

**Issue by rgknight** [sfirke/janitor#271]
I've started working a little more with `kable` and rmarkdown. It would be really nice to have a quick parser that would take snake case names and make them into proper case names that would be suitable for column headers in a table. That way, if you operate within a snake case paradigm, it can take nice names for code and make them into nice names for tables. 

Imaginary example, assuming the function were called printable names:
```
iris %>% 
  clean_names() %>%
  proper_names() %>%
  names()
```
should output
```
"Sepal Length" "Sepal Width" "Petal Length" "Petal Width" "Species"
```
Or maybe the request is to have proper case added to [snake case](https://github.com/Tazinho/snakecase)? You could skip the `clean_names()` in the example if `proper_names()` wrapped a `snakecase` function. 

Tableau's parser does this automatically. It's really nice.

**Comment by billdenney** [comment]
@rgknight, I love that idea, and I think that it may only require making more arguments for `snakecase::to_any_case()` available because it's possible with `snakecase` (see the second example in its vignette): https://cran.r-project.org/web/packages/snakecase/vignettes/caseconverters.html

**Comment by sfirke** [comment]
Some thoughts:
- I too would like to see this, I've discussed it at some length at my workplace b/c we have this need too.  Right now we `gsub` the underscores into spaces, then use `tools::toTitleCase` which leaves some words like "of" uncapitalized.  English-centric though.  `stringr::str_to_title` capitalizes all words without exempting things like "of".
- I could see it being in scope for the snakecase 📦 .  What do you think @Tazinho ?  EDIT: I see Bill points out that snakecase supports this possibility, though I might be inclined to provide `"proper"` as a case rather than expose the argument `sep_out`.

Assuming either is feasible, do you prefer `clean_names("title")` or `proper_names()` or something else?

**Comment by billdenney** [comment]
I do similar to you @sfirke for my names at work with `gsub()` and `toTitleCase()`.

I'd vote for a different function because `clean_names()` has the goal of making the names usable for programming while the other function would make the names usable for reading.  My vote for the name of that function would be `title_names()` or maybe `readable_names()`, and it could use either the `snakecase` or the `gsub()`/`toTitleCase()` method.  My use case is the latter because I'm English-speaking and like my "of"s lower case, but I don't want to vote for the package to be English-centric, so I'd vote that both methods are available, and that improvements for other languages could go to improvement of `toTitleCase()`.

**Comment by Tazinho** [comment]
I also think the easiest is to use snake case with seo_out = „ “ and and add a toTitleCase (base or stringr) behind. Currently this is out of scope for the snakecase pkg, but would be happy to see this in janitor.

**Comment by rgknight** [comment]
@Tazinho could you say more about why this is out of scope for snake case? Is it the creation of a title case engine that is out of scope? Could snake case provide a `to_proper_case()` wrapper based on existing functionality?

**Comment by Tazinho** [comment]
Hm, it is a good idea. I was just not sure about the ambiguity it might introduce, `tools::toTitleCase()` already has these disadvanteages.

However, I could include a case "title" or ("proper"?), which uses the same rules for transliteratoin as `case = "mixed"`. This would also allow *janitor* to wrap it completely. However, it is a bit sad that it would only work for english as I would basically wrap the output in `tools::toTitleCase()`. 

For further languages one could create lookup tables..here it might begin to become out of scope... Then it's just open how it fits into the interface. I think at least a new argument would be needed as I would like to keep everything in one function which keeps the same logic through the whole pkg.

**Comment by Tazinho** [comment]
Thanks for pushing this. I think it looks indeed very nice :)

``` r
# remotes::install_github("Tazinho/snakecase", force = TRUE)
library(snakecase)

to_title_case(c("on_andOn", "AndON", " and on", 
                "and so on", "seems like it works", "also abbreviations ETC"),
              abbreviations = "ETC")
#> [1] "On and on"              "And on"                
#> [3] "And on"                 "And so on"             
#> [5] "Seems Like it Works"    "also Abbreviations ETC"
```

<sup>Created on 2019-02-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by Tazinho** [comment]
Hm, seems that tools::toTitleCase() was introduced in R 3.2.0 which would increase the r version dependency for both, janitor (current is 3.1.2) and snakecase (3.1.0).

**Comment by Tazinho** [comment]
@sfirke I need you to make an urgent decision. (Regarding to failing CRAN-tests on some exotic OS I need to resubmit snakecase quickly within 2 weeks [otherwise it's taken down] and would like to include this one in the update).

So we have two options for a proper / title-case variant:
1. Just use one of mixed, parsed or upper camel case with `sep_out = ""` .(unproblematic)
2. Use `tools::toTitleCase()` as shown to posts above. (Therefore, I'd need to update the required R-Version for snakecase (from 3.1.0) and janitor (3.1.2) to 3.2). This shouldn't be a too big deal for janitor as just recently the r-version-support for the tidyverse (current dplyr needs already R 3.2) was also updated to  https://www.tidyverse.org/articles/2019/04/r-version-support/

What do you think?

**Comment by sfirke** [comment]
I will dig back into this by end of the day Tuesday and let you know! 🕐

**Comment by sfirke** [comment]
Let's do `tools::toTitleCase()` and bump the minimum required R version.  I agree that 3.2 doesn't seem unreasonable esp. if in line with dplyr.

Does that get you what you need for resubmission?  Let us know here if you want feedback on any of the snakecase-side of things, for how to generate a "proper title case"-type output.  Then the discussion can continue here on how to tackle this on the janitor side of things (a separate function like `proper_names()`, etc.) at a slower pace

**Comment by Tazinho** [comment]
Ok, it's submitted and I think janitor can just wrap it.

I submitted a bit too fast (it should have been based on snake case instead of parsed case). So, the current CRAN-implementation gives

```r
to_title_case("ALLStarGameMVP", abbreviations = c("MVP"))
[1] "ALL Star Game MVP"
```

However, it's already fixed in the dev-branch, which will give

```r
to_title_case("ALLStarGameMVP", abbreviations = c("MVP"))
[1] "All Star Game MVP"
```

**Comment by sfirke** [comment]
I think @billdenney 's massive #340 PR will close this too.  Now that `snakecase` has support for Title Case and Sentence case, a user can call `clean_names` to _un_clean the names back to Title Case at the end of their analysis, yes?  As long as we give the user access to those case options.

**Comment by billdenney** [comment]
Yes, with #340, all options to `snakecase::to_any_case()` will be exposed, so if a formatting is available there, it will be available in `clean_names()`.
