### ISSUE TITLE
adorn_total("col") still skips first column even when numeric

### ISSUE THREAD

**Issue by sydanny** [sfirke/janitor#285]
When adorning columns with a total (`adorn_totals("col")`), the first column is always skipped, even if it is numeric.

```r
df <- tibble::tribble(
    ~ a, ~ b,
      1,   2,
      3,   4
  )
df %>% adorn_totals("col")
```
Output:
```r
df
# A tibble: 2 x 2
      a     b
  <dbl> <dbl>
1     1     2
2     3     4

df %>% adorn_totals("col")
 a b Total
 1 2     2
 3 4     4
```
Expected output:
```r
df %>% adorn_totals("col")
 a b Total
 1 2     3
 3 4     7
```

This was reported as an old issue that was fixed, but here it appears to still be broken. (https://github.com/sfirke/janitor/issues/57)

**Comment by sfirke** [comment]
Thanks for filing this!  I had to re-acquaint myself with this.  I agree that it would be better if this was a more flexible function in terms of column specification.  Right now `?adorn_totals` notes:

> This function excludes the first column of the input data.frame, assuming it's a descriptive variable not to be summed.

And I think it has to work that way currently because:
```

mtcars %>%
  tabyl(cyl, gear) %>%
  glimpse()

Observations: 3
Variables: 4
$ cyl <dbl> 4, 6, 8
$ `3` <dbl> 1, 2, 12
$ `4` <dbl> 8, 4, 0
$ `5` <dbl> 2, 1, 2
```

If `adorn_totals("col")` summed that first numeric column, it would be wrong.  So I can't just switch it to sum all numeric columns.

A longer-term solution would be to allow for column selection like `dplyr::select()`, then you could say whether to sum that first numeric column.  This issue is discussed in #219 so I'll close this to keep discussion in one place.
