### ISSUE TITLE
Feature Request: Detect Columns that Map to Each Other

### ISSUE THREAD

**Issue by billdenney** [sfirke/janitor#291]
I often receive data with columns that contain either identical or effectively identical columns.

As an example, I may have a column indicating a human-readable medical laboratory test (like "Cholesterol, LDL"), and another column indicating a more computer-friendly standardized test number (called a LOINC code that may be 12345).  It would be helpful to me to have a reporter function that indicates the columns that all map to the same values.  The interface could look like:

`find_mapping_cols(x)`

where it would return a list with elements that are character vectors of columns that map to each other:

```r
foo <- data.frame(
  Lab_Test_Long=c("Cholesterol, LDL", "Cholesterol, LDL", "Glucose"),
  Lab_Test_Short=c("CLDL", "CLDL", "GLUC"),
  LOINC=c(12345, 12345, 54321),
  Person=c("Sam", "Bill", "Sam"),
  stringsAsFactors=FALSE
)
find_mapping_cols(foo)
```

That would return a list that looks like:

```r
list(c("Lab_Test_Long", "Lab_Test_Short", "LOINC"), "Person")
```

It's up to the user what they would want to do with that list (because which column of the set is most useful to keep is not obvious).

**Comment by billdenney** [comment]
I think that this is very similar to (but not quite a duplicate of) #18.

**Comment by sfirke** [comment]
The PR looks good to me.  The only big question I have is, is this a subset of a broader problem of column mapping, and would there be a non-sprawling way to cover the general case of many:1 mapping?  Say your values of LDL cholesterol and HDL cholesterol always corresponded to "Cholesterol" in a new column "Test_Category" and Glucose always corresponded to "Blood Sugars".

I will chew on this for a bit.  It would be annoying noise to be told that say, ID is many:1 with first_name because several IDs have the first_name Bill.  So high-cardinality cases may make this too tedious.  

But say you had a data.frame with one row for each of the 52 standard playing cards, this would tell you that `suit` is many:1 with `color` because Spade and Club always map to black and Heart and Diamond to red.

What do you think?  Also there's probably a lot of work done on this topic outside of R, I will do a little searching.

**Comment by sfirke** [comment]
BTW here's a nice request of sorts for the one-to-one functionality you've written so far, demonstrating that it's not only you looking for this: https://stackoverflow.com/q/52399474

**Comment by billdenney** [comment]
I was focused on the use case for an entire column of data maps to another entire column of data (or many other columns).  The more general problem is a lot harder to get right and it seems more specific, overall.  I understand and agree with the value of the understanding of the potential for understanding the mapping between values in two different columns; the harder part is how to apply it.  That feels like a different question than the one in the original request (still valid, but different).

**Comment by sfirke** [comment]
Agreed.  I'll file the many-to-one thing away as something we could do in a world with infinite time, and then I'll get on with reviewing + merging the 1:1 check.

**Comment by billdenney** [comment]
The 1:1 check needs a fix that I'm working on right now.  The testthat update could do with one final go-over (mainly the question about `adorn_totals()`).
