### ISSUE TITLE
Feature Request: Make excel_numeric_to_date() Generic

### ISSUE THREAD

**Issue by billdenney** [sfirke/janitor#310]
Currently, `excel_numeric_to_date()` requires numeric input, but as is the case with many `janitor` functions, input is often messy.

I often get files that have various formats for date and sometimes I want to use generic code to clean them up.  With that, I'd like to have `excel_numeric_to_date()` be able to take in POSIXt or Date classes.  The return value would be an appropriate of either POSIXct (if `include_time=TRUE`) or Date (if `include_time=FALSE`).

The downside to this is that things other than numbers are no longer is actually "excel numeric" to date, but a more general to date function.

If interested, I'll make a PR.

**Comment by sfirke** [comment]
Could you say more about the use case?  Would that be a convenience
function to turn a POSIXlt into a POSIXct?

**Comment by billdenney** [comment]
My use case is more that I receive lots of files with varying levels of quality but generally similar column naming.  If I get 5 Excel files, 3 of them may have good "Date" columns where the values are imported as dates (either `Date` or one of the `POSIXt` classes) while 2 of them may import as numeric.  I'd like to be able to use the same code on all files and have the same class output (either `Date` or `POSIXct`) regardless of the way that the import occurred.

**Comment by sfirke** [comment]
Ahhh okay, I have experienced that too.  So the change would be that
excel_numeric_to_date can be called on a Date or POSIX and while it
basically doesn't do anything, it succeeds, allowing for blanket use of the
function on a batch of data (instead of needing to test for whether the
columns are of class numeric).  IS that right?  It wouldn't change the
behavior of the function for its current users, just make it more versatile
for this kind of `map`-ping across multiple files that _should_ be the same
but may not be?

**Comment by billdenney** [comment]
Almost exactly as you described with the one difference that it would make the output consistent including for Date and POSIXt objects.

So, if you put in a Date and ask for the output to also include time, it will output a POSIXt object.  If you put in a POSIXt object and request a date only format, it will return a Date.

I think that I’m hearing that your answer is yes, you’re interested, so I’ll make a PR where the specifics will be clearer.

**Comment by jzadra** [comment]
I think this is a great idea, but I'd vote for the default output to be lubridate type date and datetime objects.  POSIX is very non-intuitive to work with, especially for newer users.

**Comment by billdenney** [comment]
I just double-checked, and I'm pretty sure that lubridate uses base `Date` and `POSIXct` classes (but makes them much easier to work with).

**Comment by sfirke** [comment]
What do you think about making this a whole new function, that takes a mix
of different inputs that could be dates and smoothes them out to be
consistent? There has been some demand for that in past issues. I held off
because it seemed kind of hairy, but this discussion is headed there.

**Comment by billdenney** [comment]
It is headed there, and it is hairy, but it is also very useful.  How about the following interface (please suggest a name change for the function, if you have even a slight preference toward something else):

`convert_to_date()`

And

`convert_to_datetime()`

Note that I’m specifically avoiding `as_*` because those are taken by lubridate.

They would take a single argument, `x`, and make that argument into either a Date object or a POSIXct object.

If x is a numeric, go to `excel_numeric_to_date()`.

If x is POSIXt or Date, cast as appropriate based on the function called (_date or _datetime).  For date to datetime, the time will be midnight UTC.

For character, it gets very messy very quickly.  If it looks like a character representation of a number, convert to numeric then pass to `excel_date_to_numeric()`.  If it looks like yyyy-mm-dd hh:mm:ss then use the lubridate `ymd_hms()` functions (allowing for no “:ss” or no “hh:mm:ss” and for a T instead of the space to look more like ISO8601.  Also, the character method would allow a function or list of functions to be provided to do the conversion (assumed to be the lubridate family of ymd_hms) where all non-NA values must be successfully converted to get an output.

FYI, for the character conversion, I would not recommend going directly to `ymd_hms()` without checking the pattern because even in Vitale’s opinion (the author of lubridate) the parser is too lax in some of its parsing which will yield unintended results in some scenarios.

Thoughts?

**Comment by billdenney** [comment]
@jzadra  and @sfirke, I'm curious about your opinions on the PR I just made.

**Comment by jzadra** [comment]
I've tried to break it but so far had no luck, nice work! I like that you can specify the character format and decide how to deal with unconvertibles!  

A couple thoughts/questions that aren't really errors but just worth considering perhaps:

- I do notice that it doesn't handle a numeric excel date stored as a character, i.e. `convert_to_date(1)` works but convert_to_date("1") doesn't.  I don't know excel very well, is there ever a case where it would store an excel numeric in the same column with characters and so output the excel numeric as character?

- Currently it can't handle mixing formats.  For instance `convert_to_date(c(1, "1985-08-26"))` doesn't work.  Is this an expected use case that we should think about trying to handle?  I.e. a guessing function based on the format of the value?

- `convert_to_date(1)` gives "1899-12-31".  Shouldn't this be "1700-01-01"?  If so, perhaps it's due to rounding?

- Eventually it could be useful to guess at the character formats, ie handle `convert_to_date(c("1985-08-26", "8-26-1955"))`, but perhaps that's better left to the lubridate package for the future.  I'm thinking that certain guesses could be made based on character position and then range (ie greater than 12 can't be a month place, greater than 31 can't be a day place, 4 digits must be year)?  Perhaps because there's no way to guess about "3/3/12" this simply isn't possible or someone would have done it by now :).  One way to provide some of this function might be to provide a vector of character_funs, in order of priority where after the first run, any that converted to NA would be attempted with the second fun? This probably gets too messy...

**Comment by billdenney** [comment]
I'm glad that it's working for you!

In response to your thoughts:
1. A character `"1"` would be an unusual date character string in that it's a long time ago (though nothing more than that).  I debated how to manage that, and I thought that most Excel dates would be 5-digit numbers (10000 to 99999) indicating dates between 1927-05-18 and 2173-10-13.  I did this as a quality check on the dates that most dates will likely be in that range.  I didn't require the same with numbers, but maybe that inconsistency is a problem.
2. Mixing formats is related to the above.  when you do `c(1, "1985-08-26")`, it becomes `c("1", "1985-08-26")` (with the `"1"` becoming a character string).  That is part of base R, and then the answer reverts to the answer above for a character 1.
3. The Microsoft Excel date epoch begins on 1899-12-30, so 1899-12-31 is accurate for 1.
4. Guessing date formats is a hairy mess that will give errors (See https://github.com/tidyverse/lubridate/issues/552 among many other lubridate issues).  The alternate to guessing formats that I considered was, like you suggested, to allow a list of `character_fun()`s so that you could sequentially replace `NA` values with a result.  I didn't do that in the end because if the date formats are so messy that you need multiple character functions, I think that the best scenario is to write your own character conversion function which will handle all the scenarios in your data.

**Comment by jzadra** [comment]
> I'm glad that it's working for you!
> 
> In response to your thoughts:
> 
> 1. A character `"1"` would be an unusual date character string in that it's a long time ago (though nothing more than that).  I debated how to manage that, and I thought that most Excel dates would be 5-digit numbers (10000 to 99999) indicating dates between 1927-05-18 and 2173-10-13.  I did this as a quality check on the dates that most dates will likely be in that range.  I didn't require the same with numbers, but maybe that inconsistency is a problem.

Aha!  I see now, and I think your handling of this makes sense.  But I agree that the inconsistency could be an issue.  One thought might be to allow extreme numbers for excel numerics but throw a warning for dates outside of a given window (-50 years and + 10 years or something?) - this could be a good feature in general to help catch typos, but again perhaps that's better left to the user to check their date ranges later?

> 2. Mixing formats is related to the above.  when you do `c(1, "1985-08-26")`, it becomes `c("1", "1985-08-26")` (with the `"1"` becoming a character string).  That is part of base R, and then the answer reverts to the answer above for a character 1.

Yes of course, I wasn't thinking.  And again your handling of this makes sense.

> 3. The Microsoft Excel date epoch begins on 1899-12-30, so 1899-12-31 is accurate for 1.
> 4. Guessing date formats is a hairy mess that will give errors (See [tidyverse/lubridate#552](https://github.com/tidyverse/lubridate/issues/552) among many other lubridate issues).  The alternate to guessing formats that I considered was, like you suggested, to allow a list of `character_fun()`s so that you could sequentially replace `NA` values with a result.  I didn't do that in the end because if the date formats are so messy that you need multiple character functions, I think that the best scenario is to write your own character conversion function which will handle all the scenarios in your data.

Agreed, there's too much guesswork to be left to a pre-determined sequence.  Better to know what guesses you are making by writing your own function in these cases.

**Comment by billdenney** [comment]
As I'm thinking more about it, it's probably reasonable to indicate to the user as part of `excel_numeric_to_date()` when their numbers should be checked because the results look unusual.  But in the end, I agree that the user is responsible for confirming that their dates are reasonable.

**Comment by sfirke** [comment]
Sorry I have been MIA, I'll look through the above this week!
