### ISSUE TITLE
feature request: custom translation of symbols such as % # in clean_names()

### ISSUE THREAD

**Issue by woodwards** [sfirke/janitor#316]
Currently clean_names() converts `%` to `percent` and `#` to `number`. Would it be possible to have an option like translate = c("%" = "pc", "#" = "no", "/" = "per")?

**Comment by sfirke** [comment]
I could see a more generalized addition, where the user can pass a list of custom replacements that take place before the rest of the clean_names processing.  It would cover your use case but do more as well, for instance I imagine it would be more accessible to users who speak languages other than English.

In terms of implementation, I think it would be a new argument `replacements` or similar, whose default value would be the current `%` = `percent` and `#` = `number`, but that could be overridden by supplying a list like `replacements = list(`%` = "percent", `#` = "no", `/` = "per")`.  Kinda like `dplyr::rename`, though because this is a single argument I think it would have to be a list unlike `rename`?

I welcome thoughts on both the purpose of this addition and the implementation.  I know lists confuse a lot of beginners, but if we provide an example it should be okay - plus I don't see a clearer way.

Also to be transparent, I don't have capacity to work on this myself.  I'd accept a pull request though if someone is up for implementing it.  @billdenney, I don't know your interest or capacity right now but I'd also trust you to either implement or code review someone else's stuff.

**Comment by woodwards** [comment]
Yes this is actually what I suggested in my post. Maybe I wasn't very clear. I think a vector would do rather than a list since all we need are strings. Something like this?

``` r
new_make_clean_names <- function(string, case = "snake", replace = c("%" = "percent", "#" = "number")){
    string %>%
        str_replace_all(replace) %>%
        make_clean_names(case)
}

c("12", "This (kg/L)", "that#2, %", "2019-10-8", "12") %>%
    new_make_clean_names()
#> Error in c("12", "This (kg/L)", "that#2, %", "2019-10-8", "12") %>% new_make_clean_names(): could not find function "%>%"
```

<sup>Created on 2019-11-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sfirke** [comment]
Ah yes I see your post does suggest that.  And neat, I did not know stringr::str_replace_all, that might make this a lot easier!

**Comment by sfirke** [comment]
We could borrow this usage example from `?stringr::str_replace_all`:

```
# If you want to apply multiple patterns and replacements to the same
# string, pass a named vector to pattern.
fruits %>%
  str_c(collapse = "---") %>%
  str_replace_all(c("one" = "1", "two" = "2", "three" = "3"))

```

**Comment by jzadra** [comment]
Is there a compelling case to bring this functionality into janitor rather than just using dplyr::rename_all() with str_replace_all?

**Comment by woodwards** [comment]
Maybe not but most packages offer some level of customisation and this seems natural to me.

**Comment by billdenney** [comment]
I just saw this as I was looking through older issues and noticed the request to review a PR.

@jzadra, I think that the main reason to bring the functionality into janitor is that it would expose something that is hard-wired in janitor (https://github.com/sfirke/janitor/blob/9a88626e92dfa515b205293e23ce3f790ff1f6ae/R/make_clean_names.R#L50-L58) and make it a user-controlled option without adding extra complexity for the user.  A secondary benefit is that it will 

@woodwards, if you can make the PR, I can review it.  Please make the PR such that it is backward-compatible (i.e. uses the current defaults as the new input default value).  Also, can you please assist by incorporating the code simplifications from #303 in your PR, as applicable?  (Preferably, incorporate the applicable parts of #303 as a first commit and your changes subsequent to that.)

**Comment by woodwards** [comment]
@billdenney I have not made a PR (pull request?) before so not really sure what is involved. I have moved on from this and working on other things at the moment.

**Comment by billdenney** [comment]
@woodwards, fair enough that you've moved on from this.  If it is of interest to come back to it, please respond to the original issue, and we can help guide you through it.

The gist of it is to:
1. fork the repository to your account,
2. clone your copy of the repository to your local computer,
3. make the code and documentation changes like you would with any text editor or IDE,
4. ensure that you have tests for your code changes,
5. push the changes back to your copy of the repository, and
6. click the wizard button that will show up to help make a pull request.

That may sound like many steps, but outside of the code changes part, it can be done in <5 minutes when you get the hang of it (I'd guess ~10 minutes if you're familiar with git but not GitHub).  This isn't intended to pressure you to make the pull request-- just to let you know the process in case you want to do it in the future either here or in a different project.

**Comment by woodwards** [comment]
What do tests #4 look like?

**Comment by billdenney** [comment]
That is generating tests to test all new features of your code. In this case, it would be adding something to https://github.com/sfirke/janitor/blob/master/tests/testthat/test-clean-names.R

In this case, it would involve calling the new `make_clean_names()` with the `replace` argument set to something other than the default and confirming that the results were different as expected with the different argument.
