### ISSUE TITLE
The column "percent" in a one-way tabyl() should be renamed to "proportion"

### ISSUE THREAD

**Issue by wordsmith189** [sfirke/janitor#342]
## Bug reports

Good afternoon,

I love tabyl()!!!! I use it every day. But when I use it in teaching, I always have to point out that the reported "percent" isn't actually percent - it's the proportion. Would it be possible to either multiply the number by 100 and thus report actual percent, or rename the column?

Many thanks!

**Comment by sfirke** [comment]
You are right :stuck_out_tongue_winking_eye:  This was raised in #300 and elsewhere.

You can do the former, multiply by 100, like this:
```
mtcars %>% tabyl(am) %>% adorn_pct_formatting()
```
To be strictly correct, it would have to start off "proportion", then the `adorn_pct_formatting()` operation would retitle the column to "percent".  But having an operation like that retitle a column seems too heavy-handed.  I guess if it started as "proportion" and stayed "proportion" once it was percent, would that be less wrong in total?

All that to say, I think you're right, but I'm inclined to leave it as is for the same reasons as stated in #300.  BUT, if I was ever going to change this, it would be this week since janitor 2.0.0 is coming out soon and it will have breaking changes so is the place to break more things.  I'll leave open for comment for a week to see what others think.

**Comment by jzadra** [comment]
My two cents: it seems like this is a minor convention that would introduce way too much complexity than it's worth.  I and the people I work with are so used to thinking of percents as 0-1 values that this never even crossed my mind. I prefer to use proportions because in R those are still numeric. I apply percent formatting at the very, very last step for presentation.

Most notably, if the column name were to change from proportion to percent after adorning percent formatting, it has high potential to break code if the user was doing things with the tables downstream, and decided at some point they wanted to use percent formatting earlier.

**Comment by sfirke** [comment]
Yep I think in this case, the consistency outweighs any advantage to renaming, so I'll close this.
