### ISSUE TITLE
NA frequency tabyl fails

### ISSUE THREAD

**Issue by bshor** [sfirke/janitor#343]
Tabyl works great. But I often need to know the table of missing data of a particular variable. But instead I get a cryptic error.

```
df %>% tabyl(var, show_na = F)
```
works but this doesn't:

```
df %>% tabyl(is.na(var), show_na = F)
```

Which fails saying it can't find `var`.

Even though this works:
```
prop.table(table(is.na(df$var)))
```

**Comment by sfirke** [comment]
Glad you like it!  Your problem is caused by a mixup.  `tabyl` can accept a data.frame piped in, as you have in your working example.  But then you are mixing in that `is.na()` which wants a single variable.

Luckily `tabyl` also can accept a vector, so you can use the same syntax that's working for you at the end: `tabyl(is.na(mtcars$cyl))` is equivalent to your `prop.table(table(is.na(mtcars$cyl)))`.

Or if you like to pipe:
```
mtcars %>%
  pull(cyl) %>%
  is.na %>%
  tabyl
```

**Comment by bshor** [comment]
Understood. It's just that the piping syntax isn't the same for checking for NAs as it is for a simple frequency table. The syntax IS the same for when you don't pipe. A touch confusing, but not a big deal. Thanks.
