### ISSUE TITLE
get_dupes(mtcars, weight = wt) example fails under the dev version of dplyr

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#354]
`get_dupes` has the example `mtcars %>% get_dupes(weight = wt, starts_with("cy"))`

The `weight = wt` fails under the version of dplyr currently on GitHub (and going to CRAN soon as 1.0.0).  It seems to work under the current version of dplyr on CRAN, 0.8.5.

@jzadra do you have any ideas?  The quick fix I'll make is removing the `weight = wt` argument from that example call.  That way I can proceed to meet CRAN's demand for resubmission by end of this weekend.  But if you can see what's changing in dplyr or what else could be causing that, feel free to submit a PR that reinstates showing that functionality in an example.

**Comment by jzadra** [comment]
Since I don't understand what dplyr/tidyselect did to break this, I don't feel like I can give a fully informed answer, but I would lean toward just removing it.

That renaming is certainly not at all critical, and I think would be rarely if ever used since you can always do a `rename()` before or after (frankly I think that within get_dupes is a confusing spot to chose to do it, but it was a tidyselect feature so I through it in to show that it could be done).

**Comment by sfirke** [comment]
Sounds good to me!  Let's just make this not our problem instead of learning what happened :grin:

**Comment by jzadra** [comment]
Do you want me to do a PR for this or have you got it covered?

Thanks,

Jon

--
Jonathan Zadra, PhD (he/him)
Director of Data Science
Sorenson Impact Center
David Eccles School of Business, University of Utah
www.sorensonimpact.com
(801) 581-4815
On Apr 2, 2020, 19:32 -0600, Sam Firke <notifications@github.com>, wrote:
> Sounds good to me! Let's just make this not our problem instead of learning what happened 😁
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

--

**Comment by sfirke** [comment]
I fixed it but thanks!
