### ISSUE TITLE
easy Suggestion for janitor: adorn_totals("both")  # shows row and col totals...

### ISSUE THREAD

**Issue by sfd99** [sfirke/janitor#362]
GREAT, Sam!
janitor is wonderful.

btw:
a **shortcut** to get Total Sums 
for _BOTH_ rows _AND_ cols:

mtcars %>%
tabyl(am, cyl) %>%
adorn_totals(c("row", "col"))
am 4 6 8 Total
0 3 4 12 19
1 8 3 2 13
Total 11 7 14 32

So, 
 (easy) SUGGESTION -
also allow keyword:
"**_both_**"
as param to:
adorn_totals("**_both_**")
or maybe simply:
  adorn_totals()

less coding...easier... :-)

**Comment by higgi13425** [comment]
kinda like this one. If it is not too hard to do.

**Comment by sfd99** [comment]
excellent, Sam,
hey! looking forward to it.
less keystrokes the better... :-)
**Janitor** pkg. is _so super- nice_to use...useful!!

**Comment by jzadra** [comment]
This is far simpler, but some of the discussion in #313 might be of use.

**Comment by svgsstats** [comment]
I like this suggestion as well. 

I use this package in my Intro Stats course and we bring it into the course early on.  The current method means that I need to have some explanation of vectors which isn't necessary (or desired early on).

**Comment by sfirke** [comment]
Okay, let's do it, with `where = "both"` being the equivalent to `where = c("col", "row")`.  I think `row` should probably remain the default, (a) since that's less breakage (b) only `row` makes sense on a one-way tabyl.

This is relatively basic, if anyone wants to submit a pull request with this change + add it to NEWS + add a test, I'd welcome it!
