### ISSUE TITLE
Is there a way to combine multiple 1-way tabyls together?

### ISSUE THREAD

**Issue by ksw9** [sfirke/janitor#387]
Thanks for a great package. I was wondering if there is a way to combine multiple 1-way tabyls together for formatting? For example, I'd like to summarize patient population characteristics in a single table. 

Thank you!

**Comment by sfirke** [comment]
Thanks for the note!  Could you say more about this use case, maybe showing an example of what the final combined table would look like?

**Comment by ksw9** [comment]
Thanks!
For example, it would be great to be able to combine the following tabyls, s1 and s4, with several others into a large dataframe that preserves the formatting across variables of different types so that I can export an image, with grid.table (or something else). Is there a straightforward way to do this? Thank you!

```
s1 <- pop_sub %>%
tabyl(sex) %>%
adorn_pct_formatting()
s1

sex  n percent
   F 46   31.7%
   M 99   68.3%

s4 <- pop_sub %>%
tabyl(binned_age) %>%
adorn_pct_formatting()
s4

 binned_age  n percent
       < 18  8    5.5%
      18-25 24   16.6%
      26-35 38   26.2%
      36-55 53   36.6%
      55-70 21   14.5%
       > 70  1    0.7%
```

**Comment by sfirke** [comment]
Sorry not to respond here.  If this is still relevant, can you open a Discussion thread? https://github.com/sfirke/janitor/discussions  I'm closing it here since I don't think it needs anything on the software development front.  If you'd want to combine those vertically, I'd suggest using `dplyr::bind_rows` and moving the first column name into a "variable" column.
