### ISSUE TITLE
count rows as empty if entries are NA *or* blank

### ISSUE THREAD

**Issue by bbolker** [sfirke/janitor#424]
It would be nice to have an option in `remove_empty()` to remove rows that are composed entirely of *either* `NA` values or are zero-length (e.g. empty strings). (Possibly consider all-whitespace strings to be "empty" as well?)   This is a fairly common pattern in data frames read in from Excel.

The example below isn't particularly "tidy", nor entirely integrated with the `remove_empty()` machinery, but I think shows what I have in mind.

```r
library(tidyverse)
library(janitor)

dd <- tibble(x=c(LETTERS[1:5],rep("",2)),
             y=c(1:5,rep(NA,2)))
remove_empty(dd,"rows")      ## doesn't remove rows 6 &  7 (they're not all-NA)

emptyrows2 <- function(x) {
   apply(x,1,
   function(x) {
        y <- unlist(x)
        all(is.na(y) | nchar(y)==0)
    })
}

dd <- dd[!emptyrows2(dd),]
```

**Comment by billdenney** [comment]
This is something that I experience, too.  I have a bit of hesitation because it opens up a can of worms (and therefore many different function arguments) which may be solved more simply with data pre-treatment.

My typical method is to turn values that should be `NA` into `NA` before sending it into `remove_empty()`.  My method would be below.  The difference between pre-treatment and your suggested method is that empty strings and all-whitespace strings are now `NA` in the final result.  In my experience, if a string should be considered `NA` for row-emptiness, then it should be set to `NA`.  But, I understand that may not always be the case.

Does the below work for you, or do you think that new arguments like:  `whitespace_empty=FALSE` (`TRUE` means to consider all-whitespace or empty strings as empty) and `empty_extra=c()` (where these values would also be considered missing, and they could be anything) would be worth the addition?

``` r
library(tidyverse)
library(janitor)
#> 
#> Attaching package: 'janitor'
#> The following objects are masked from 'package:stats':
#> 
#>     chisq.test, fisher.test

my_data <-
  tibble(
    A=c("A", " ", "", "B", NA),
    B=c(NA, " ", "A", NA, NA)
  )

# just row 5 is removed
remove_empty(my_data, which="rows")
#> # A tibble: 4 x 2
#>   A     B    
#>   <chr> <chr>
#> 1 "A"    <NA>
#> 2 " "   " "  
#> 3 ""    "A"  
#> 4 "B"    <NA>

# Rows 2 and 5 are removed, and row 3 column A now has an NA value.
my_data %>%
  mutate_all(.funs=trimws) %>%
  mutate_all(.funs=na_if, y="") %>%
  remove_empty(which="rows")
#> # A tibble: 3 x 2
#>   A     B    
#>   <chr> <chr>
#> 1 A     <NA> 
#> 2 <NA>  A    
#> 3 B     <NA>
```

<sup>Created on 2021-02-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by bbolker** [comment]
Thanks, a student suggested this same approach, and I agree that it's better to do simple (and more flexible) pre-processing rather than encumbering `remove_empty()` with more complexity. My only suggestion would be to add an example like this to the help file?  (I'd be happy to submit a PR if you like.)

```
dd <- tibble(x=c(LETTERS[1:5],NA,rep("",2)),
             y=c(1:5,rep(NA,3)),
             z=rep(NA,8))

(dd
    %>% mutate(across(is.character,~na_if(trimws(.),"")))
    %>% remove_empty(c("rows","cols"))
)
```

I like the compactness of `~na_if(trimws(.),"")` but I guess tastes will differ.

**Comment by billdenney** [comment]
I'm still gaining familiarity with `across()`, so it's not in my natural repertoire.  Yes, a PR would be helpful!

**Comment by bbolker** [comment]
Me too, but since it's supposed to be the New Thing I've been trying to adopt it.
