### ISSUE TITLE
Feature suggestion: function to remove columns based on missing percentage

### ISSUE THREAD

**Issue by jzadra** [sfirke/janitor#446]
I have some large tables that have say, 99.8 % missing.  I'm wondering if it would be useful to have a function similar to `remove_empty()` that would remove columns based on a cutoff of percent missing?

ie `remove_missing_cutoff(df, cutoff = .99)`

**Comment by sfirke** [comment]
Maybe add a `cutoff = 1` argument to `remove_empty` rather than creating a new function?  I don't really see a downside to that and I see how it could have been useful to me in the past, especially when playing around with sparse data sets and ML models.

**Comment by billdenney** [comment]
I would lean toward adding a cutoff argument to `remove_empty`, as well.

I think that the `cutoff` argument would make sense for rows, but it would be less clear that it makes sense for columns.  Technically, yes both can be treated the same way, but it's not clear that's the right consideration.  At least for my data, 1% empty rows is a much different consideration than 1% empty columns.  But, that can also be up to the user to decide.

Also, I think that we should only support `cutoff != 1` when `which` is specified to either rows or columns.  Otherwise, it would depend on which order we remove, rows or columns.  It would be consistent, but it could be confusing to the user.  And, rather than have bug reports saying "Why isn't it removing the empty rows that I expected it to?" I'd suggest we only allow one direction with a cutoff at a time.

**Comment by sfirke** [comment]
Entirely agreed, Bill.

**Comment by billdenney** [comment]
I just implemented it.  Lemme know if it works for you.
