### ISSUE TITLE
avoid collision of µg and mg becoming mg in `make_clean_names`

### ISSUE THREAD

**Issue by IndrajeetPatil** [sfirke/janitor#448]
This harmless change while renaming columns created quite the storm in a teacup for my analysis, so thought I would check if this is the expected behavior or if there is any way for the function to anticipate measurement units and rename accordingly:

``` r
# µg: micrograms, mg: milligrams
janitor::make_clean_names(c("x_µg", "y_mg"))
#> [1] "x_mg" "y_mg"
```

<sup>Created on 2021-07-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

P.S. I am showing only two names for a minimal reprex and my actual dataframe is much more complex and with a ton of variables, so renaming columns before using `janitor` is possible but quite cumbersome. 

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.1.0 (2021-05-18)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Berlin               
#>  date     2021-07-09                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                       
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.1.0)               
#>  backports     1.2.1      2020-12-09 [1] CRAN (R 4.1.0)               
#>  cli           3.0.0      2021-06-30 [1] CRAN (R 4.1.0)               
#>  crayon        1.4.1      2021-02-08 [1] CRAN (R 4.1.0)               
#>  DBI           1.1.1      2021-01-15 [1] CRAN (R 4.1.0)               
#>  digest        0.6.27     2020-10-24 [1] CRAN (R 4.1.0)               
#>  dplyr         1.0.7      2021-06-18 [1] CRAN (R 4.1.0)               
#>  ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.1.0)               
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.1.0)               
#>  fansi         0.5.0      2021-05-25 [1] CRAN (R 4.1.0)               
#>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.1.0)               
#>  generics      0.1.0      2020-10-31 [1] CRAN (R 4.1.0)               
#>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.1.0)               
#>  highr         0.9        2021-04-16 [1] CRAN (R 4.1.0)               
#>  htmltools     0.5.1.1    2021-01-22 [1] CRAN (R 4.1.0)               
#>  janitor       2.1.0      2021-01-05 [1] CRAN (R 4.1.0)               
#>  knitr         1.33       2021-04-24 [1] CRAN (R 4.1.0)               
#>  lifecycle     1.0.0      2021-02-15 [1] CRAN (R 4.1.0)               
#>  lubridate     1.7.10     2021-02-26 [1] CRAN (R 4.1.0)               
#>  magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.1.0)               
#>  pillar        1.6.1      2021-05-16 [1] CRAN (R 4.1.0)               
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.1.0)               
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.1.0)               
#>  R6            2.5.0      2020-10-28 [1] CRAN (R 4.1.0)               
#>  Rcpp          1.0.7      2021-07-07 [1] CRAN (R 4.1.0)               
#>  reprex        2.0.0      2021-04-02 [1] CRAN (R 4.1.0)               
#>  rlang         0.4.11     2021-04-30 [1] CRAN (R 4.1.0)               
#>  rmarkdown     2.9        2021-06-15 [1] CRAN (R 4.1.0)               
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.1.0)               
#>  snakecase     0.11.0     2019-05-25 [1] CRAN (R 4.1.0)               
#>  stringi       1.6.2      2021-05-17 [1] CRAN (R 4.1.0)               
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.1.0)               
#>  styler        1.4.1.9003 2021-07-08 [1] Github (r-lib/styler@c7c978e)
#>  tibble        3.1.2      2021-05-16 [1] CRAN (R 4.1.0)               
#>  tidyselect    1.1.1      2021-04-30 [1] CRAN (R 4.1.0)               
#>  utf8          1.2.1      2021-03-12 [1] CRAN (R 4.1.0)               
#>  vctrs         0.3.8      2021-04-29 [1] CRAN (R 4.1.0)               
#>  withr         2.4.2      2021-04-18 [1] CRAN (R 4.1.0)               
#>  xfun          0.24       2021-06-15 [1] CRAN (R 4.1.0)               
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.1.0)               
#> 
#> [1] /Users/patil/Library/R/x86_64/4.1/library
#> [2] /Library/Frameworks/R.framework/Versions/4.1/Resources/library
```

</details>

**Comment by sfirke** [comment]
Interesting case, thanks for the minimal reprex.  I see how it's bad for `µg` and `mg` to both become `mg`!

This is one way around it:
```
janitor::make_clean_names(c("x_µg", "y_mg"), replace = c("µg" = 'micrograms'))
[1] "x_micrograms" "y_mg"    
```
That is better and more robust than renaming each one manually.  I could see value in having `µg` added to the standard values of `replace`, to become `mcg` or `micrograms`, the way `%` becomes `percent` but can be overridden.  It feels a little bit of a slippery-slope, will-it-cause-unforeseen-problems area but realistically I'd bet that in the vast majority of cases it would be an improved treatment of `µg`.  As to slippery slope, other cases can be evaluated individually.

Thoughts from others?

**Comment by IndrajeetPatil** [comment]
Thanks for the quick response and providing a workaround! That is definitely helpful short-term.

> I could see value in having `µg` added to the standard values of replace, to become `mcg` or `micrograms`, the way `%` becomes `percent` but can be overridden. 

That'd be great! I'd vote for `micrograms`. More verbose, but clearer than `mcg`.

**Comment by billdenney** [comment]
I have the exact same problem as I often use micrograms units (and I did a lot of the recent writing on `make_clean_names()`, so I have thought a lot about this specific problem).

The mu symbol is a tough one.  There are two Unicode characters that are visually that character, one is "mu" ("\u03bc") and the other is micro ("\u00b5").  In my experience, people tend to use the character based on visual comparison rather than accurately being the micro vs mu symbol.

People who are translating from Greek text to ASCII will probably want the "m" mapping while I would guess people working in technical fields would prefer the "micro" mapping.  I see the slippery slope in "µg" mapping, too, because then we would need to do the same for all other units out there (what about micrometers, micromolar, etc.

As a separate point, putting Unicode characters is an unfortunate no-no (see r-lib/roxygen2#1121 where I specifically discuss the mu/micro issue and r-lib/roxygen2/issue#1186), so putting this into the package documentation will cause headaches with CRAN submission.

Mainly for the CRAN submission reasons, I'd vote not to put this into the main code base.  (Maybe a vignette would be helpful?)

**Comment by billdenney** [comment]
One thought to prevent "storm in a teacup" issues, perhaps we should warn if we find a mu or micro symbol in the names and warn

"Watch out!  The mu/micro symbol was changed to 'm' by `make_clean_names()`, that could cause confusion with units if you expected to see a 'u'."

I would vote for that as a potential change since I agree that the problem is likely to be a common one, and mg vs ug is a bad change to make, in general.  (I wish that there were a more satisfying way to handle it that would play well with CRAN.)

**Comment by jzadra** [comment]
It might also be nice to include a tip about the replace argument in the warning.

**Comment by billdenney** [comment]
I just made a PR to issue warnings.  Lemme know if it works well for you.
