### ISSUE TITLE
excel_numeric_to_date converts incorrectly for dates between 1900-01-01 through 1900-02-28

### ISSUE THREAD

**Issue by aetheogamout** [sfirke/janitor#478]
Because of the 1900-02-29 bug in how excel represents dates in windows, representation of dates from 1900-01-01 and 1900-02-28 effectively use a different origin than dates 1900-03-01 on. 

The result of this is that dates produced by excel_numeric_to_date(1:59) are off by one day from the date as shown in excel:

in R:
`excel_numeric_to_date(1)`
[1] "1899-12-31"

in a modern version of excel convert the number 1 to a date:

`=TEXT(1, "yyyy-mm-dd")`
1900-01-01

**Comment by billdenney** [comment]
You're right.  This was fixed in #422, and it will be included in the next janitor release.  If you need to use it now, you can do `remotes::install_github("sfirke/janitor")` to get the current development version.

As an aside (see #423), excel date handling before 1900-03-01 is poor (searching the internet for "excel older dates" and similar will show many issues).

**Comment by sfirke** [comment]
Maybe a sign that it's time for a CRAN release 🤔

**Comment by aetheogamout** [comment]
Thanks! and apologies - I misread what #422 is fixing

**Comment by billdenney** [comment]
@aetheogamout , No worries at all.  Excel dates present all sorts of unique problems.

**Comment by billdenney** [comment]
@sfirke, if it's CRAN release time, I'm gonna make a couple more PRs.  Hopefully, I can do those later today.
