### ISSUE TITLE
Suggestion: get_dupes results should be sorted by dupe_count descending

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#493]
## Feature requests

Sort the results of `get_dupes` by `dupe_count`.

## Remarks

Right now it sorts alphabetically by the grouping variable.  But usually I then add `%>% arrange(desc(dupe_count))` to start with the most-duplicated combination.  I suppose this would potentially be a breaking change for some use cases.  But I think it is ultimately more useful than the alphabetical sort.

## Example
`mtcars %>% get_dupes(cyl)`

In my result, the group with `cyl = 8` that has 14 records would appear first.

This would be easy to implement.  Thoughts from others?

**Comment by billdenney** [comment]
It makes sense to me.  When I use `get_dupes()`, the goal is either to confirm that there are no duplicates or to manually inspect them.  Neither of my use cases is broken with your suggested change, and the manual inspection is improved.

My one addition would be to break a tie by sorting alphabetically second so that there is a consistent output order.

**Comment by jzadra** [comment]
Yes I think this is a good enhancement.
