### ISSUE TITLE
Remove timezone support from `sas_numeric_to_date()`

### ISSUE THREAD

**Issue by billdenney** [sfirke/janitor#583]
While working on #582, there was an issue with timezone tests in `sas_numeric_to_date()`.

Looking at https://communities.sas.com/t5/Ask-the-Expert/Tips-and-Tricks-for-Working-with-Dates-and-Times-in-SAS-Q-amp-A/ta-p/813974, it appears that SAS likely (but not definitively) doesn't support storing time zones and it likely stores the timezone as the current time zone. The documentation that I can find is not clear.

Therefore, I plan to remove timezone support from the function and always use UTC timezones. That seems like the least-bad choice because a SAS file sent to a computer in a timezone that has different daylight saving time method would likely get different results, based on my reading.

**Comment by billdenney** [comment]
The implementation in #584 doesn't remove timezone support but gives a warning when it's used with any timezone other than UTC.

**Comment by sfirke** [comment]
> The implementation in #584 doesn't remove timezone support but gives a warning when it's used with any timezone other than UTC.

I'm reviewing #584 and want to make sure I understand:

1) is the idea that the input `tz`  value is ignored and UTC used for the conversion, with the only current use of the `tz` argument being to warn users who have legacy code using that argument?

2) If that's right, does that mean this will be a breaking change for those users because the same input will now result in a warning and a different result?

**Comment by billdenney** [comment]
1. `tz` is not ignored. Now UTC is used by default but the user can specify a different `tz` value.
2. It is a breaking change that `tz` used to be "" by default and now it's "UTC". And, yes, there is a warning which is technically a breaking change (but the warning doesn't change the calculation results).
