### ISSUE TITLE
sort columns & rows

### ISSUE THREAD

**Issue by vincentarelbundock** [sfirke/janitor#66]
Cool package, thanks!

One thing I often do when cleaning up data is sorting rows and columns. Would be nice to have one command to sort rows by columns col1, col2, ..., and then arranges the columns such that the index variables appear first, and the rest of the columns are sorted alphabetically. Something like:

```
out = dat %>% arrange(col1, col2)
v = colnames(out)[!colnames(out) %in% c('col1', 'col2')]
v = c('col1', 'col2', sort(v))
out = out[, v]
```

**Comment by sfirke** [comment]
Here's some thinking aloud...

This does it in dplyr:

```
mtcars %>%
  arrange(mpg, wt) %>%
  select(mpg, wt, noquote(order(names(.))))
```

If you have a lot of sorting variables and only want to specify them once:

```
vars <- c("mpg", "wt")

mtcars %>%
  arrange_(vars) %>%
  select_(.dots = c(vars, noquote(order(names(.)))))
```

I'd rather keep the two actions (sort and reorder) decoupled, instead of combining into one function, per the [Tidyverse Manifesto:](https://github.com/hadley/tidyverse/blob/master/vignettes/manifesto.Rmd)

> Strive to keep functions as simple as possible (but no simpler!). Generally, each function should do one thing well, and you should be able to describe the purpose of the function in one sentence.

To keep it more flexible for users with different purposes.  And at least for now, I don't want to include a wrapper function specifically for that last line - even that feels like combining two actions (move vars to the front and then sort the others) in a way that would be more applicable if decomposed into two functions.  There's already `everything()` from dplyr for reordering columns, maybe the clearest way to write this in your analysis would be:

```
mtcars %>%
  arrange(mpg, wt) %>%
  select(noquote(order(names(.)))) %>%
  select(mpg, wt, everything())
```

Perhaps wrapping `select(noquote(order(names(.))))` as a function `alphabetize_columns` would be useful, depending on how widespread that operation is.

**Comment by vincentarelbundock** [comment]
All of this sounds reasonable. It's important to limit feature creep.
