### ISSUE TITLE
feature request: show column AND row percentages after crosstab

### ISSUE THREAD

**Issue by randomgambit** [sfirke/janitor#86]
Hello there! Happy new year!

`janitor::crosstab` is great but I find very annoying that one can see row percentages, or column percentages, but not the two at the same time. In particular, showing frequencies AND row/col percentages would be far more effective. 

A little example from `Stata` http://www.stata.com/help.cgi?tabulate+twoway

```
. webuse citytemp2
(City Temperature Data)

. tab region agecat

    Census |              agecat
    Region |     19-29      30-34        35+ |     Total
-----------+---------------------------------+----------
        NE |        46         83         37 |       166 
   N Cntrl |       162         92         30 |       284 
     South |       139         68         43 |       250 
      West |       160         73         23 |       256 
-----------+---------------------------------+----------
     Total |       507        316        133 |       956 


. tab region agecat, row col

+-------------------+
| Key               |
|-------------------|
|     frequency     |
|  row percentage   |
| column percentage |
+-------------------+

    Census |              agecat
    Region |     19-29      30-34        35+ |     Total
-----------+---------------------------------+----------
        NE |        46         83         37 |       166 
           |     27.71      50.00      22.29 |    100.00 
           |      9.07      26.27      27.82 |     17.36 
-----------+---------------------------------+----------
   N Cntrl |       162         92         30 |       284 
           |     57.04      32.39      10.56 |    100.00 
           |     31.95      29.11      22.56 |     29.71 
-----------+---------------------------------+----------
     South |       139         68         43 |       250 
           |     55.60      27.20      17.20 |    100.00 
           |     27.42      21.52      32.33 |     26.15 
-----------+---------------------------------+----------
      West |       160         73         23 |       256 
           |     62.50      28.52       8.98 |    100.00 
           |     31.56      23.10      17.29 |     26.78 
-----------+---------------------------------+----------
     Total |       507        316        133 |       956 
           |     53.03      33.05      13.91 |    100.00 
           |    100.00     100.00     100.00 |    100.00 
```

everything at once! yay! I think `crosstab` should just do that.
What do you think?

Thanks!

**Comment by randomgambit** [comment]
there could simply be an option `stats='all'` that shows the table above if the user needs it. My guess is that everybody will be using this all the time. So convenient.

**Comment by kent37** [comment]
Take a look at descr::CrossTable, it does exactly this.

**Comment by randomgambit** [comment]
thanks @kent37 but, seriously? how many different packages do we need to do the same stuff over and over again? I think `janitor` should/could do that natively, otherwise what is the point of having a package devoted to cross tabulations if it does not implement the most basic functions?

**Comment by sfirke** [comment]
This definitely would not go in `crosstab` because that function feeds `adorn_crosstab` - need to keep one numeric value per cell coming from `crosstab`.

But I don't think this belongs in `adorn_crosstab` either.  I find the table above of full outputs to be too busy to read, but I'll admit that's personal opinion.  My bigger concern is that the above structure is no longer at the most basic level of tidyness, with one variable in each row and one in each column.  The multiple values per cell is untidy for further operations.  (I'm not counting the format `x (y%)` because that's a common thing to encounter and still fits in one "cell" of a results table.)

I don't see how that above output gets passed to `kable` and dressed up nicely in an RMarkdown report.  That `agecat` label hanging out on the top is nice - I wish I could incorporate it into `crosstab` where right now the 2nd variable goes unnamed in the result - but it is multiple "cells" wide and doesn't fit in a data.frame object.

Like @kent37 points out, there are several other packages that print big Stata or SPSS style multi-way % crosstabs to console.  I've meant to blog about the 10+ crosstab functions that already exist in other packages.  I wrote `adorn_crosstab` here because it stays in a neat data.frame vs. printing a text output, while also providing some tidyverse-type functionality that `table` is missing.
