### ISSUE TITLE
checking that a join didn't alter the number of records

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#95]
This would be a defensive `check_` for assertive programming.  There are two common scenarios where I want the result of a `_join()` to have the same number of rows as the `x` table:

1. `left_join` - if there are duplicate values in the right table, it'll increase the number of rows in the left
2. `inner_join` - if all values in the left table (order doesn't matter, for this to be sensible the user should specify the larger table as the left one) don't have a match in the right, the number of rows will decrease

Is that in scope for this package?  It is a common data cleaning task.

**Comment by rgknight** [comment]
Case 1 is one of my primary use cases for `assert_uniq` or whatever we are calling it now -- I run `assert_uniq` after joining to make sure the correct vars still uniquely ID the df. 

Case 2 is interesting. There might be a function here for that case. I do that join a lot but I'm not as rigorous as I should be about checking it. I do a lot of random anti_joins, but it's not well organized. 

I could see `check_equal_rows()` being easy to implement. However, what would the warning message say? Do you care about whether the key values are equal? So you would want to know which keys are missing in the message? 

A more strict version would be `check_keyvalues(df1, df2, keys() )`  where it checks that all of the distinct combinations of the keys exist in both dataframes.

**Comment by sfirke** [comment]
Do you have the code for `assert_unique`?  That seems like an easy one to implement.  Maybe it would take a data.frame plus at least one variable, and confirm that all combinations of those variables are unique.

Or would multiple variables cause each one to be checked for uniqueness?  E.g., if you have:
```
data_frame(person_id = c(1, 1), month = c("Jan", "Feb"))
#> # A tibble: 2 Ã— 2
#>   person_id month
#>       <dbl> <chr>
#> 1         1   Jan
#> 2         1   Feb
```

and run `df %>% assert_unique(person_id, month)` does it choke because person_id is not unique?  Or allow it because the combinations are unique?  Maybe we do something like the syntax for `tidyr::complete()` where you can name columns solo to have them checked for no duplicates, or specify a set of variables to be checked for unique combinations?

**Comment by sfirke** [comment]
This also has me wondering if someone hasn't already implemented this well.  I'd want to make sure there's a good reason for us doing it, I'm feeling conscious of redundant R packages these days.

**Comment by rgknight** [comment]
`assert_unique` checks that variables are jointly unique. If you wanted to check that a list of variables was independently unique, you would apply it to the list of columns. 

`assertr` recently pushed out `is_uniq`. It tests variables independently, so it's a little different. They do have a workaround for testing whether variables are jointly unique that I think they developed based on an issue I created. 

I haven't pushed anything out for this because I want to check out `assertive` more to see whether it would fill this need.

Ultimately, dplyr's planned `set_keys()` will likely soak up most of my use cases. 

So I agree re: duplication of effort. However, Janitor doesn't exist to do things that weren't possible before Janitor -- it exists to make things more accessible. I will do more due diligence on whether this is necessary, but there may still be room for a straightforward `check_unique` and `assert_unique` function within our approach, such that newer users don't have to be confused by `assertr`'s use of synonyms for their primary verbs (why?!?).

**Comment by sfirke** [comment]
A set of checks like this is not a bad idea, but I'm not going to get to this in the indefinite future, so closing.

This package has nice function for "loud" joins to see what happened: https://github.com/adamMaier/reviewr

Doesn't have assertive checks to then establish that a join still behaves how it should and how it has before (e.g., no introduced duplicates).
